travis:
  secure:
    BINSTAR_TOKEN: aP01EkpktB93Xo1V7G/jFeB8I9/7iu4qgvuYCZk5XLjoUZiKkKCgB1svMiKEOXPeyzUd0kBMM5Ala4I3STmW7pJ88WEDv1YYpObMD4TO5V5nbOjdYu2EVhDAh58GBqnGsaFVzZAqplHbI0p2d2WEOxQxTqMFBl6zHRG1Kwo/lbejYp4zmeOypvcr4VPsM/Atbp8a3ZLlDhcGR8jVsxrFnpnoluYpVVJXxcgj4M/aBXHMeX7svjfSLcFnCBx2Kl9FUoCbMCjxRonE4uUNU91TvjmLYYPTMSmaP3n7KhlTyEU/Ns5vlBQp0bH6SQdGJnLkA6OghMxJbN0NfzRGFvekSsjaCF+vPm1Uanip+LKdeU+1wP6jEMYoiHJQNPhnDcVUeqDXRNwMWxwn24PsDXzEmlmdrHwTrp9xoytmAZx58niKB21i/X8Ik/QnCdX9eeiL6KGCI0dHk23nPi2w/SZRY4CPCefgwd1X2w6p2QNL9JkzOqgCXdic9gZK3SAAY3lqvTu3mSNaUndI5cKktZ2J1IUiQB7YwVnkke3/D2HtrbCoZV8Mulx87Ix2BHom/YIs+o3pTMBapAlezb8pglFB0GKEF/kEhEEbDMsrAE0AzLdjiElXhuKytD88PQeztTOobz63HV9WN80/sg82bD0gvjdYFg+gofUgOcaC/h8gHHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
