travis:
  secure:
    BINSTAR_TOKEN: JGEpxkpW990CsR9Ae0KbXCo3kNIAMs68UBhfJp80f/8CNKKbNHmgymQXOylfdTBGEMsoorLZRuctxD7SHaYomVuFPlb9cwVJc7o0ureH87AQEEI2to0VRQgXb+b+PKpnltvVik2eThpJadA7fhmGFJiMYxihKcoKdDVBHpnJYNv1yJcX7ZYj2GQpXmmRGL3Ff5vI8nz0rY9SE2jNMbl77muNSBL+GQYx9naQnurzT5YsGPX2azzbViqa9ZrsztQvNQs/da+1Agm+aHlD4FNYrD4SNUeA5zD7Lo5VyCdQZfjNtnFkrf8am7AhBbE7gz0W9u6eYSyDQrvTFZh+2wFEkfkwb761Wcm+CA9emgo3J/L742fhgIP/Y8ZTtMKOH4bLic85KYkbJ5aog9DkB9RHmz4iUvgjF0z7FSHB5AW0Xhv7S8RTUq0sC9hZNM+iNthftLYv5mk+JMOt3h3F7duTJBuCcPMAm6Pnw7WkDJILR9VK/iicmyjF1+eCUWbU1XSS62q1uTpM9z6UfB+1KQHzzZOZALd+QW0ukrpA1F0kSay1rLhkyu9KJ0T+dIihdOR1mIDoGqMeRlQlNtke9ObEAwss7ZLji+KyorGVwb3R2WmxX81pnl3TFgDdYdQ9WjAo5YQBWqA/NJoM/vP3xmK3NetideO9RvL0dM4dIrieTx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
